# Generated by Django 5.1.1 on 2024-09-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='education',
            field=models.CharField(default=1, max_length=155),
            preserve_default=False,
        ),
    ]
