# Generated by Django 5.1.1 on 2024-09-05 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_education'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='education',
            new_name='mother_name',
        ),
    ]
