# Generated by Django 5.1.1 on 2024-09-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patient_father_name_alter_patient_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='age',
        ),
        migrations.AddField(
            model_name='patient',
            name='birth_date',
            field=models.IntegerField(default=1, verbose_name='data de nascimento'),
            preserve_default=False,
        ),
    ]
