# Generated by Django 5.1.1 on 2024-09-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_remove_patient_age_patient_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='cpf',
            field=models.CharField(default=1, max_length=155),
            preserve_default=False,
        ),
    ]
